# Generated by Django 4.1.1 on 2023-07-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PN', 'Paneer'), ('LS', 'Lassi'), ('CZ', 'Cheeze'), ('IC', 'Ice-Creams'), ('KF', 'Kulfi'), ('MS', 'Milkshake'), ('GH', 'Ghee'), ('CR', 'Curd'), ('ML', 'Milk')], max_length=2),
        ),
    ]
