# Generated by Django 4.1.1 on 2023-07-04 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('KF', 'Kulfi'), ('IC', 'Ice-Creams'), ('MS', 'Milkshake'), ('CR', 'Curd'), ('ML', 'Milk'), ('PN', 'Paneer'), ('LS', 'Lassi'), ('CZ', 'Cheeze')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('_state', models.CharField(choices=[('Goa', 'Goa'), ('Kerala', 'Kerala'), ('Banglure', 'Banglure'), ('Kochi', 'Kochi'), ('Assam', 'Assam'), ('Tamilnadu', 'Tamilnadu'), ('Delhi', 'Delhi'), ('Bihar', 'Bihar'), ('Chennai', 'Chennai'), ('Karnataka', 'Karnataka')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
