# Generated by Django 4.1.1 on 2023-07-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='_state',
            field=models.CharField(choices=[('Tamilnadu', 'Tamilnadu'), ('Chennai', 'Chennai'), ('Goa', 'Goa'), ('Banglure', 'Banglure'), ('Kerala', 'Kerala'), ('Karnataka', 'Karnataka'), ('Kochi', 'Kochi'), ('Delhi', 'Delhi'), ('Assam', 'Assam'), ('Bihar', 'Bihar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ML', 'Milk'), ('CZ', 'Cheeze'), ('KF', 'Kulfi'), ('PN', 'Paneer'), ('LS', 'Lassi'), ('GH', 'Ghee'), ('CR', 'Curd'), ('MS', 'Milkshake'), ('IC', 'Ice-Creams')], max_length=2),
        ),
    ]
