# Generated by Django 4.1.1 on 2023-07-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customer__state_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='_state',
            field=models.CharField(choices=[('Assam', 'Assam'), ('Tamilnadu', 'Tamilnadu'), ('Chennai', 'Chennai'), ('Banglure', 'Banglure'), ('Karnataka', 'Karnataka'), ('Bihar', 'Bihar'), ('Kerala', 'Kerala'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Kochi', 'Kochi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('KF', 'Kulfi'), ('LS', 'Lassi'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('GH', 'Ghee'), ('CR', 'Curd'), ('CZ', 'Cheeze'), ('IC', 'Ice-Creams'), ('ML', 'Milk')], max_length=2),
        ),
    ]
