# Generated by Django 4.1.1 on 2023-07-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customer__state_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='_state',
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Kochi', 'Kochi'), ('Assam', 'Assam'), ('Goa', 'Goa'), ('Chennai', 'Chennai'), ('Kerala', 'Kerala'), ('Tamilnadu', 'Tamilnadu'), ('Bihar', 'Bihar'), ('Banglure', 'Banglure'), ('Delhi', 'Delhi'), ('Karnataka', 'Karnataka')], default='kerala', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CZ', 'Cheeze'), ('KF', 'Kulfi'), ('CR', 'Curd'), ('ML', 'Milk'), ('GH', 'Ghee'), ('PN', 'Paneer'), ('IC', 'Ice-Creams'), ('LS', 'Lassi'), ('MS', 'Milkshake')], max_length=2),
        ),
    ]
