# Generated by Django 4.1.1 on 2023-07-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_customer__state_customer_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Assam', 'Assam'), ('Kochi', 'Kochi'), ('Kerala', 'Kerala'), ('Banglure', 'Banglure'), ('Tamilnadu', 'Tamilnadu'), ('Goa', 'Goa'), ('Bihar', 'Bihar'), ('Karnataka', 'Karnataka'), ('Delhi', 'Delhi'), ('Chennai', 'Chennai')], default='kerala', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CZ', 'Cheeze'), ('ML', 'Milk'), ('GH', 'Ghee'), ('KF', 'Kulfi'), ('CR', 'Curd'), ('PN', 'Paneer'), ('MS', 'Milkshake'), ('LS', 'Lassi'), ('IC', 'Ice-Creams')], max_length=2),
        ),
    ]
