# Generated by Django 4.1.1 on 2023-07-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customer_state_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Kerala', 'Kerala'), ('Banglure', 'Banglure'), ('Bihar', 'Bihar'), ('Assam', 'Assam'), ('Chennai', 'Chennai'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Karnataka', 'Karnataka'), ('Kochi', 'Kochi'), ('Tamilnadu', 'Tamilnadu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LS', 'Lassi'), ('PN', 'Paneer'), ('KF', 'Kulfi'), ('MS', 'Milkshake'), ('CR', 'Curd'), ('ML', 'Milk'), ('GH', 'Ghee'), ('CZ', 'Cheeze'), ('IC', 'Ice-Creams')], max_length=2),
        ),
    ]
