# Generated by Django 4.1.1 on 2023-07-05 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_alter_customer_state_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Banglure', 'Banglure'), ('Assam', 'Assam'), ('Delhi', 'Delhi'), ('Karnataka', 'Karnataka'), ('Goa', 'Goa'), ('Chennai', 'Chennai'), ('Kochi', 'Kochi'), ('Tamilnadu', 'Tamilnadu'), ('Kerala', 'Kerala'), ('Bihar', 'Bihar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GH', 'Ghee'), ('IC', 'Ice-Creams'), ('KF', 'Kulfi'), ('CR', 'Curd'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('LS', 'Lassi'), ('ML', 'Milk'), ('CZ', 'Cheeze')], max_length=2),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
