# Generated by Django 4.1.1 on 2023-07-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_customer_state_alter_product_category_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Tamilnadu', 'Tamilnadu'), ('Kerala', 'Kerala'), ('Goa', 'Goa'), ('Bihar', 'Bihar'), ('Chennai', 'Chennai'), ('Assam', 'Assam'), ('Karnataka', 'Karnataka'), ('Banglure', 'Banglure'), ('Kochi', 'Kochi'), ('Delhi', 'Delhi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PN', 'Paneer'), ('ML', 'Milk'), ('MS', 'Milkshake'), ('GH', 'Ghee'), ('LS', 'Lassi'), ('CZ', 'Cheeze'), ('IC', 'Ice-Creams'), ('CR', 'Curd'), ('KF', 'Kulfi')], max_length=2),
        ),
    ]
