# Generated by Django 4.1.1 on 2023-07-10 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_alter_customer_state_alter_product_category_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Kerala', 'Kerala'), ('Banglure', 'Banglure'), ('Bihar', 'Bihar'), ('Tamilnadu', 'Tamilnadu'), ('Karnataka', 'Karnataka'), ('Assam', 'Assam'), ('Delhi', 'Delhi'), ('Kochi', 'Kochi'), ('Chennai', 'Chennai')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Deliverd', 'Deliverd'), ('Cancel', 'Cancel)'), ('Pending', 'Pending'), ('On the way', 'On the Way'), ('Accepted', 'Accepted')], default='Pending..', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MS', 'Milkshake'), ('IC', 'Ice-Creams'), ('KF', 'Kulfi'), ('CR', 'Curd'), ('ML', 'Milk'), ('PN', 'Paneer'), ('CZ', 'Cheeze'), ('GH', 'Ghee'), ('LS', 'Lassi')], max_length=2),
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
